/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package improvecaro;

import java.awt.Color;

/**
 *
 * @author Acer
 */
public class GameNotfication extends javax.swing.JPanel {

    /**
     * Creates new form GameNotfication
     */
    private ImproveCaro parent;
    
    public GameNotfication(ImproveCaro parent) {
        initComponents();
        this.parent = parent;
        lblBg.setBackground(new Color(0, 0, 0, 170));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBg = new javax.swing.JLabel();

        setLayout(null);

        lblBg.setBackground(new java.awt.Color(0, 0, 0));
        lblBg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblBg.setOpaque(true);
        lblBg.setPreferredSize(new java.awt.Dimension(1920, 1080));
        add(lblBg);
        lblBg.setBounds(0, 0, 1920, 1080);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBg;
    // End of variables declaration//GEN-END:variables
}
