/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bst;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author CE170499 Nguyen Le Tai Duc
 */
public class BSTDemoFrame extends javax.swing.JFrame {

    BSTree tree;
    BSTPaper p;

    /**
     * Creates new form GUI
     */
    public BSTDemoFrame() {
        initComponents();

        //Maximize the frame
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

        tree = new BSTree(1800, 60);
        p = new BSTPaper(tree, 1800, 60);
        paper.setSize(1800, 500);
        paper.setLayout(new BorderLayout());
        paper.add(p, BorderLayout.CENTER);
        txtTraversal.setEditable(false);
    }

    public int randomNumber(int min, int max) {
        return (int) ((Math.random()) * (max - min + 1)) + min;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNodeValue = new javax.swing.JTextField();
        btnAddRandom = new javax.swing.JButton();
        btnAddNode = new javax.swing.JButton();
        btnPreOrder = new javax.swing.JButton();
        btnInOrder = new javax.swing.JButton();
        btnPostOrder = new javax.swing.JButton();
        txtTraversal = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBFS = new javax.swing.JButton();
        btnDFS = new javax.swing.JButton();
        btnBalancingTree = new javax.swing.JButton();
        paper = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Confirguration"));
        jPanel1.setPreferredSize(new java.awt.Dimension(1900, 192));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Node's Value");

        txtNodeValue.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtNodeValue.setText("0");
        txtNodeValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNodeValueActionPerformed(evt);
            }
        });

        btnAddRandom.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddRandom.setText("Add Random Value");
        btnAddRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRandomActionPerformed(evt);
            }
        });

        btnAddNode.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddNode.setText("Add Node");
        btnAddNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNodeActionPerformed(evt);
            }
        });

        btnPreOrder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPreOrder.setText("Pre-order");
        btnPreOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreOrderActionPerformed(evt);
            }
        });

        btnInOrder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnInOrder.setText("In-order");
        btnInOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInOrderActionPerformed(evt);
            }
        });

        btnPostOrder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPostOrder.setText("Post-order");
        btnPostOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostOrderActionPerformed(evt);
            }
        });

        txtTraversal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTraversal.setText("Traversal:");

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBFS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBFS.setText("BFS");
        btnBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBFSActionPerformed(evt);
            }
        });

        btnDFS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDFS.setText("DFS");
        btnDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDFSActionPerformed(evt);
            }
        });

        btnBalancingTree.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnBalancingTree.setText("Balacing tree");
        btnBalancingTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalancingTreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTraversal, javax.swing.GroupLayout.PREFERRED_SIZE, 1816, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNodeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddNode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddRandom))
                        .addGap(18, 18, 18)
                        .addComponent(btnBalancingTree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPreOrder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnInOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPostOrder))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBFS, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDFS, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddNode)
                            .addComponent(btnAddRandom)
                            .addComponent(btnPreOrder)
                            .addComponent(btnInOrder)
                            .addComponent(btnPostOrder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearch)
                            .addComponent(btnDelete)
                            .addComponent(btnClear)
                            .addComponent(btnBFS)
                            .addComponent(btnDFS)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNodeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnBalancingTree, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(txtTraversal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        paper.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        paper.setPreferredSize(new java.awt.Dimension(1800, 700));

        javax.swing.GroupLayout paperLayout = new javax.swing.GroupLayout(paper);
        paper.setLayout(paperLayout);
        paperLayout.setHorizontalGroup(
            paperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paperLayout.setVerticalGroup(
            paperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1880, Short.MAX_VALUE)
                    .addComponent(paper, javax.swing.GroupLayout.DEFAULT_SIZE, 1880, Short.MAX_VALUE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paper, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNodeValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNodeValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNodeValueActionPerformed

    private void btnAddRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRandomActionPerformed
        // TODO add your handling code here:
        p.addNode(randomNumber(0, 100));
    }//GEN-LAST:event_btnAddRandomActionPerformed

    private void btnAddNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNodeActionPerformed
        // TODO add your handling code here:
        p.addNode(Integer.parseInt(txtNodeValue.getText()));
    }//GEN-LAST:event_btnAddNodeActionPerformed

    private void btnPreOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreOrderActionPerformed
        // TODO add your handling code here:
        tree.preOrder();
        txtTraversal.setText("Pre-Order Traversal: " + tree.getResult());
    }//GEN-LAST:event_btnPreOrderActionPerformed

    private void btnInOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInOrderActionPerformed
        // TODO add your handling code here:
        tree.inOrder();
        txtTraversal.setText("In-Order Traversal: " + tree.getResult());
    }//GEN-LAST:event_btnInOrderActionPerformed

    private void btnPostOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostOrderActionPerformed
        // TODO add your handling code here:      
        tree.postOrder();
        txtTraversal.setText("Post-Order Traversal: " + tree.getResult());
    }//GEN-LAST:event_btnPostOrderActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        tree.search(Integer.parseInt(txtNodeValue.getText()));
        p.getTree().setPath(tree.getPath());
        p.repaint();

        String result = "Search result: ";
        Iterator<BSTNode> iteration = tree.getPath().iterator();
        if (!iteration.hasNext()) {
            result += "Not found!!";
        } else {
            while (iteration.hasNext()) {
                result += iteration.next().getData() + "";
                if (iteration.hasNext()) {
                    result += " -> ";
                } else {
                    result += ".";
                }
            }
        }
        txtTraversal.setText(result);

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        tree.search(Integer.parseInt(txtNodeValue.getText()));
        p.getTree().setPath(tree.getPath());
        p.repaint();

        String result = "Search result: ";
        Iterator<BSTNode> iteration = tree.getPath().iterator();
        if (!iteration.hasNext()) {
            result += "Not found!!";
        } else {
            while (iteration.hasNext()) {
                result += iteration.next().getData() + "";
                if (iteration.hasNext()) {
                    result += " -> ";
                } else {
                    result += ".";
                }
            }
        }
        if (!result.equalsIgnoreCase("Search result: Not found!!")) {
            if (JOptionPane.showConfirmDialog(this,
                    "Do you really want delete the node '" + txtNodeValue.getText() + "' ?", "Warning", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                p.deleteNode(Integer.parseInt(txtNodeValue.getText()));
            }
        }
        txtTraversal.setText(result);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this,
                "Do you really want delete the tree '" + txtNodeValue.getText() + "' ?", "Warning", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            p.clear();
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBFSActionPerformed
        // TODO add your handling code here:
        tree.BFS();
        txtTraversal.setText("BFS Traversal: " + tree.getTraversalResult());
    }//GEN-LAST:event_btnBFSActionPerformed

    private void btnDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDFSActionPerformed
        // TODO add your handling code here:
        tree.DFS();
        txtTraversal.setText("DFS Traversal: " + tree.getTraversalResult());
    }//GEN-LAST:event_btnDFSActionPerformed

    private void btnBalancingTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalancingTreeActionPerformed
        // TODO add your handling code here:
        p.balancing();
    }//GEN-LAST:event_btnBalancingTreeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BSTDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BSTDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BSTDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BSTDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BSTDemoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNode;
    private javax.swing.JButton btnAddRandom;
    private javax.swing.JButton btnBFS;
    private javax.swing.JButton btnBalancingTree;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDFS;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInOrder;
    private javax.swing.JButton btnPostOrder;
    private javax.swing.JButton btnPreOrder;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel paper;
    private javax.swing.JTextField txtNodeValue;
    private javax.swing.JTextField txtTraversal;
    // End of variables declaration//GEN-END:variables
}
